# This is a basic workflow to help you get started with Actions

name: arm64-linux

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04-arm

    env:
      testenv: "abc123"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      # default dir
      - run: /bin/ls -la ./; pwd

      # Runs a single command using the runners shell
      - name: display env
        run:
          env

      - name: $GITHUB_ENV
        run: |
          ls -la $GITHUB_ENV
          echo "PATH="$HOME/.cargo/bin:$PATH"" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge -y needrestart || true
          sudo apt install -y bash wget curl openssl
          sudo ln -svf bash /bin/sh
          #sudo dpkg -L google-cloud-cli-anthoscli
          #sudo dpkg -L google-cloud-cli
          sudo df -h
          sudo df -h
          sudo uname -a

          
      - run: mkdir -p 1/2/3/4/5/6

      - run: cd 1/2/3/4/5 ; pwd

      - run: pwd ; ls -la

      - name: test working-directory
        working-directory: 1/2/3/4
        run: |
          echo "set working-directory: 1/2/3/4"
          pwd ; ls -la

      - run: |
          sudo apt update -y
          sudo apt install -y wget curl openssl bash
          sudo apt install -y make gcc g++ m4 pkg-config perl libperl-dev groff-base dpkg-dev cmake
          sudo apt install -y autoconf autoconf-archive autogen automake autopoint autotools-dev libtool m4 bison flex
          sudo apt install -y llvm-dev libclang-dev
          sudo git clone https://github.com/mcmilk/7-Zip-zstd.git
          cd 7-Zip-zstd/CPP/ && sudo CC="clang" CXX="clang++" OUTDIR="$PWD/build-clang" ./build-lx.sh

      #- run: sudo df -h
      # - run: sudo du -h --max-depth=1 --exclude={/proc,/sys,/dev,/run} / | sort -h
      #- run: sudo du -h --max-depth=1 /usr | sort -h
      #- run: sudo du -h --max-depth=1 /usr/local | sort -h
      #- run: sudo du -h --max-depth=1 /usr/lib | sort -h
      #- run: sudo systemctl list-unit-files
