# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    env:
      testenv: "abc123"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      # default dir
      - run: /bin/ls -la ./; pwd

      # Runs a single command using the runners shell
      - name: display env
        run:
          env

      - name: $GITHUB_ENV
        run: |
          ls -la $GITHUB_ENV
          echo "PATH="$HOME/.cargo/bin:$PATH"" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge -y needrestart || : 
          sudo systemctl status -l postgresql.service
          sudo systemctl status -l mysql
          sudo systemctl status -l mysqld
          sudo apt autoremove --purge -y '^php.*'
          sudo apt autoremove --purge -y --allow-remove-essential $(dpkg -l | grep -i -E 'firefox|firebird|google-chrome-stable' | awk '{print $2}' | sort -V | uniq | paste -sd" ")
      - run: mkdir -p 1/2/3/4/5/6

      - run: cd 1/2/3/4/5 ; pwd

      - run: pwd ; ls -la

      - name: test working-directory
        working-directory: 1/2/3/4
        run: pwd ; ls -la
      - name: chronyd
        run: |
          sudo apt list | grep -i chrony
          #sudo find /etc/ -type f | grep -i chrony
          echo
          cat /etc/chrony/chrony.conf
          echo
          sudo systemctl status -l chrony
          sudo systemctl stop chrony
          sudo sed 's|^refclock.*|#&|g' -i /etc/chrony/chrony.conf
          sudo sed '1i \server time.cloudflare.com iburst minpoll 4 maxpoll 5 nts' -i /etc/chrony/chrony.conf
          sudo sed '2i \server time.google.com iburst minpoll 4 maxpoll 5' -i /etc/chrony/chrony.conf
          sudo sed '3i \server time.apple.com iburst minpoll 4 maxpoll 5' -i /etc/chrony/chrony.conf
          cat /etc/chrony/chrony.conf
          sudo systemctl start chrony
          sleep 10; sudo chronyc sources; sleep 2; chronyc tracking; sudo chronyc makestep
          sudo systemctl status -l chrony

      - name: list packages
        run: |
          sudo dpkg -l | grep -iE 'docker|container|podman|runc|crun|moby'
          sudo dpkg -l | grep -iE 'google|chrome|firefox|libmono|microsoft|mysql|postgresql|snap'

      - run: sudo df -h

      - name: purge
        run: sudo apt autoremove --purge -y '^docker.*' '^container.*' crun runc '^podman.*' firefox google-chrome-stable '^libmono-.*' '^mono-.*' '^mysql-.*' '^postgresql-.*' '^php.*'
      
      - run: sudo df -h
        # - run: sudo du -h --max-depth=1 --exclude={/proc,/sys,/dev,/run} / | sort -h
      - run: sudo du -h --max-depth=1 /usr | sort -h
      - run: sudo du -h --max-depth=1 /usr/local | sort -h
      - run: sudo du -h --max-depth=1 /usr/lib | sort -h
      - run: sudo systemctl list-unit-files

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
